const fs = require('fs');

const nav = '<nav style="position:fixed;top:0;left:0;right:0;z-index:9999;background:#ffffff;border-bottom:1px solid #e5e7eb;padding:0 20px;height:56px;display:flex;align-items:center;justify-content:space-between;font-family:Inter,-apple-system,sans-serif;box-shadow:0 1px 3px rgba(0,0,0,0.08);"><a href="index.html" style="font-weight:700;font-size:15px;color:#0ABF53;text-decoration:none;letter-spacing:-0.3px;white-space:nowrap;">Adyen Checkout API</a><button onclick="this.nextElementSibling.style.display=this.nextElementSibling.style.display===\'flex\'?\'none\':\'flex\'" style="display:none;background:none;border:1px solid #e5e7eb;border-radius:6px;padding:6px 10px;cursor:pointer;font-size:13px;color:#374151;" id="mobile-menu-btn">Menu</button><div id="nav-links" style="display:flex;gap:4px;align-items:center;"><a href="index.html" style="padding:6px 10px;border-radius:6px;font-size:13px;color:#374151;text-decoration:none;font-weight:500;white-space:nowrap;">Overview</a><a href="authentication.html" style="padding:6px 10px;border-radius:6px;font-size:13px;color:#374151;text-decoration:none;font-weight:500;white-space:nowrap;">Authentication</a><a href="getting-started.html" style="padding:6px 10px;border-radius:6px;font-size:13px;color:#374151;text-decoration:none;font-weight:500;white-space:nowrap;">Getting Started</a><a href="api-reference.html" style="padding:6px 10px;border-radius:6px;font-size:13px;color:#374151;text-decoration:none;font-weight:500;white-space:nowrap;">API Reference</a><a href="errors.html" style="padding:6px 10px;border-radius:6px;font-size:13px;color:#374151;text-decoration:none;font-weight:500;white-space:nowrap;">Errors</a><a href="changelog.html" style="padding:6px 10px;border-radius:6px;font-size:13px;color:#374151;text-decoration:none;font-weight:500;white-space:nowrap;">Changelog</a><a href="api-reference.html" style="background:#0ABF53;color:white;padding:8px 14px;border-radius:6px;font-size:13px;font-weight:600;text-decoration:none;white-space:nowrap;">API Reference</a></div><style>@media(max-width:768px){#mobile-menu-btn{display:block !important;}#nav-links{display:none;position:fixed;top:56px;left:0;right:0;background:#fff;flex-direction:column;padding:12px;border-bottom:1px solid #e5e7eb;gap:4px !important;z-index:9998;}#nav-links a{display:block;padding:10px 14px !important;}}</style></nav>';
const offset = '<style>body{padding-top:56px !important;} .menu-content{top:56px !important;} redoc-search{top:56px !important;}</style>';

let html = fs.readFileSync('_site/api-reference.html', 'utf8');
html = html.replace('<body>', '<body>' + nav + offset);
fs.writeFileSync('_site/api-reference.html', html);
console.log('Nav injected into API reference');
